### ISSUE TITLE
[Error] MTLBuffer has problems by updating them!

### ISSUE THREAD

**Issue by MrScautHD** [ppy/veldrid#59]
Version: (Latest on Nuget)
Os: MacOS
Backend: Metal

Hello!
I tried today my render framework for every backend and i saw just for Metal i got a error about `MTLBuffers` when i try to update them.

ERROR:
![grafik](https://github.com/user-attachments/assets/b0abd93a-c306-4dca-8714-c1e4038dec61)

CODE:
![grafik](https://github.com/user-attachments/assets/d0fca4e0-0832-46d8-8806-2c3e54f7c7f9)

**Comment by frenzibyte** [comment]
As per the error message you're getting, the buffer cannot be updated from the CPU. You'll either have to create a staging buffer (`BufferUsage.Staging`) that you populate with data from the CPU and queue a GPU command to copy from the staging buffer to your target buffer (`CommandList.CopyBuffer`), or make your target buffer CPU-accessible (by appending the `BufferUsage.Dynamic` flag when creating the buffer).

**Comment by MrScautHD** [comment]
thx, that fixed it.

But as i see right now my framework is not working with Metal.
Do you maybe know what can do this error?

Metal:
![grafik](https://github.com/user-attachments/assets/ba73a2ed-c29f-40fb-8fcd-ee9a9696c906)

On any other GraphicsBackend:
![grafik](https://github.com/user-attachments/assets/318f2d93-e267-454a-9a58-13d1f61fd522)

**Comment by frenzibyte** [comment]
You will have to debug through this yourself unfortunately. macOS offers Metal debugging tools embedded within Xcode, all you have to do is run Xcode, go to the top toolbar and locate an option to run an executable with Xcode attached (usually named "Debug executable), and configure the run settings to have Metal debugging enabled, then you will see the Metal icon next to the debug tools at the top of the run terminal.

See https://developer.apple.com/documentation/xcode/metal-debugger. Let me know if you need a video showcasing how to do this.

**Comment by MrScautHD** [comment]
thx allot!

**Comment by MrScautHD** [comment]
> You will have to debug through this yourself unfortunately. macOS offers Metal debugging tools embedded within Xcode, all you have to do is run Xcode, go to the top toolbar and locate an option to run an executable with Xcode attached (usually named "Debug executable), and configure the run settings to have Metal debugging enabled, then you will see the Metal icon next to the debug tools at the top of the run terminal.
> 
> See https://developer.apple.com/documentation/xcode/metal-debugger. Let me know if you need a video showcasing how to do this.

Do you maybe have a video showcasing for me?

**Comment by frenzibyte** [comment]
https://github.com/user-attachments/assets/418845fc-c6c1-4b27-af8b-46c830bbf21e

Environment variables are redundant since the default is Veldrid/Metal nowadays.
